#!bin/bash

USERID=$(id -u)
TIMESTAMP=$(date)
SCRIPT_NAME=$(echo "$0")
LOGFILE=/tmp/$TIMESTAMP-$SCRIPT_NAME.log

if [ $USERID -ne 0 ]
then 
    echo "your not a root user"
exit 1
else
    echo "your in root user"
fi

VALIDATE(){
    if [ $1 -ne 0 ]
    then
        echo "$2.....FAILURE"
        exit 1
    elase
        echo "$2.....SUCCES"
    fi
}

dnf install mysql -y &>>$LOGFILE
VALIDATE $? "installing of mysql"

dnf install git -y &>>$LOGFILE
VALIDATE $? "installing of git"